### ISSUE TITLE
PHP Library

### ISSUE THREAD

**Issue by pete-dev** [microsoftgraph/php-connect-rest-sample#18]
Is Microsoft plannng to convert this to a maintained library (like [azure-activedirectory-library-for-python](https://github.com/AzureAD/azure-activedirectory-library-for-python) or [Android SDK](https://github.com/microsoftgraph/msgraph-sdk-android)), or is it up to PHP developers to create their own libraries to access Microsoft's REST API?

**Comment by PaulStubbs** [comment]
Hi, yes we plan to deliver a PHP library for the Microsoft Graph. You can follow the list of planned libraries/SDKs from the Microsoft Graph developer site [Microsoft Graph Samples & SDKs](http://graph.microsoft.io/en-us/code-samples-and-sdks)
