### ISSUE TITLE
oAuth Issue

### ISSUE THREAD

**Issue by mckrti** [microsoftgraph/php-connect-rest-sample#36]
I am getting the following errors:

( ! ) Notice: Use of undefined constant clientId - assumed 'clientId' in C:\wamp\impact-research\files\app\oauth.php on line 30

( ! ) Notice: Use of undefined constant clientSecret - assumed 'clientSecret' in C:\wamp\impact-research\files\app\oauth.php on line 31

( ! ) Notice: Use of undefined constant redirectUri - assumed 'redirectUri' in C:\wamp\impact-research\files\app\oauth.php on line 32

( ! ) Notice: Use of undefined constant urlAuthorize - assumed 'urlAuthorize' in C:\wamp\impact-research\files\app\oauth.php on line 33

( ! ) Notice: Use of undefined constant urlAccessToken - assumed 'urlAccessToken' in C:\wamp\impact-research\files\app\oauth.php on line 34

( ! ) Notice: Use of undefined constant urlResourceOwnerDetails - assumed 'urlResourceOwnerDetails' in C:\wamp\impact-research\files\app\oauth.php on line 35

( ! ) Notice: Use of undefined constant scopes - assumed 'scopes' in C:\wamp\impact-research\files\app\oauth.php on line 36

( ! ) Warning: Cannot modify header information - headers already sent by (output started at C:\wamp\impact-research\files\app\oauth.php:34) in C:\wamp\impact-research\files\app\oauth.php on line 46

I already tried the fix mentioned here: Issue #30 But it didn't seem to help.

**Comment by cbales** [comment]
Can you check that you've got the latest version of this? schrinkel submitted a PR (#31) that resolved this issue.

**Comment by jamescro** [comment]
Closing for now. Please reopen if this continues to be an issue.
