### ISSUE TITLE
a little outdated

### ISSUE THREAD

**Issue by symoN5** [microsoftgraph/php-connect-rest-sample#42]
Hello,

how about updating this example to the newest laravel 5.5LTS version?
The current version is 5.2

**Comment by jamescro** [comment]
Thanks for the feedback. We'll put this work item in our backlog.

**Comment by symoN5** [comment]
Nice, the biggest problem is with PHP7.1 the ircmaxell\random-lib libary is deprecated :/

**Comment by robinmalik** [comment]
I just followed the guide. Using PHP 7.1.11 on Windows. Visiting localhost:8000 generates the "Connect to Microsoft Graph" button but clicking that results in:

`ErrorException in AbstractMcryptMixer.php line 75:
Function mcrypt_module_open() is deprecated`

This is being generated by oauth.php.

**Comment by jasonjoh** [comment]
@GhulamKhalique we are archiving this sample as it is no longer being maintained. We're replacing it with https://github.com/microsoftgraph/msgraph-training-phpapp (which uses PHP7.2 and current Laravel).
