### ISSUE TITLE
Integrating into Website (PHP)

### ISSUE THREAD

**Issue by GhulamKhalique** [microsoftgraph/php-connect-rest-sample#47]
I wanted to integrate provided API in my Angular JS project with php as backend. I am unable to integrate it due to some issues. Can someone guide as to which steps I need to follow in order to integrate it in my website. Thanks

**Comment by jasonjoh** [comment]
@GhulamKhalique we are archiving this sample as it is no longer being maintained. We're replacing it with https://github.com/microsoftgraph/msgraph-training-phpapp.
